# File: compose.yaml
# Description: Prod starlite deployment
#
# Author: Derek Garcia

name: starlite
services:

  api:
    image: starlite-api
    container_name: starlite-api
    pull_policy: never  # always use local build
    build: api
    networks: [ starlite-net ]

  web:
    image: starlite-web
    container_name: starlite-web
    pull_policy: never  # always use local build
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: online
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    networks: [ starlite-net ]

  web-offline:
    image: starlite-web-offline
    container_name: starlite-web-offline
    pull_policy: never # always use local build
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: offline
    ports:
      - "80:80"
    profiles: [ "offline" ]
    networks: [ starlite-net ]


networks:
  starlite-net:
    name: starlite-net
