server {
    listen 80;

    server_name starlite;

    root /usr/share/nginx/html;
    index index.html;

    # Angular routing (client-side routes fall back to index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
